(cl:defpackage rosplan_dispatch_msgs-msg
  (:use )
  (:export
   "<ACTIONDISPATCH>"
   "ACTIONDISPATCH"
   "<COMPLETEPLAN>"
   "COMPLETEPLAN"
   "<ACTIONFEEDBACK>"
   "ACTIONFEEDBACK"
   "<PLANGOAL>"
   "PLANGOAL"
   "<PLANACTIONRESULT>"
   "PLANACTIONRESULT"
   "<PLANACTIONGOAL>"
   "PLANACTIONGOAL"
   "<PLANRESULT>"
   "PLANRESULT"
   "<PLANACTIONFEEDBACK>"
   "PLANACTIONFEEDBACK"
   "<PLANACTION>"
   "PLANACTION"
   "<PLANFEEDBACK>"
   "PLANFEEDBACK"
  ))

